#这里是dworld的配置文件
#此版本的配置文件适配 dworld0.0.4 build04
-----------------------------------------------------------------------------
EventTip: true #是否开启玩家事件检测,开启后下方设置才会生效
Fish: true #是否禁止钓鱼,true为禁止
Fly: true #是否禁止飞行,true为禁止
Bed: true #是否阻止玩家睡觉,true为阻止
Chest: true #是否开启菜单,true为开启
-----------------------------------------------------------------------------
ChestTip: true #是否开启菜单检测,包括/home功能
ChestMessage: 这里是默认菜单标题 #菜单的标题,必须开启菜单检测此项才会起作用!
Config Version: 6 #配置文件的版本